In [0]:
import pandas as pd
import zipfile
import numpy as np
import re
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords,wordnet
from nltk.stem import WordNetLemmatizer
import string
from sklearn.decomposition import NMF,LatentDirichletAllocation 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix


In [2]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [0]:
data = zipfile.ZipFile('/content/enron-email-dataset.zip')

In [0]:
df = pd.read_csv(data.open('emails.csv'))

In [5]:
df.head()

file                                            message
0     allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1    allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...
2   allen-p/_sent_mail/100.  Message-ID: <24216240.1075855687451.JavaMail.e...
3  allen-p/_sent_mail/1000.  Message-ID: <13505866.1075863688222.JavaMail.e...
4  allen-p/_sent_mail/1001.  Message-ID: <30922949.1075863688243.JavaMail.e...

In [0]:
stopwords = set(stopwords.words('english'))


In [0]:
lem = WordNetLemmatizer()

def toktoktok(text):  
  text=text.lower()
  text=re.sub('[^A-Za-z]', " ", text)
  text = lem.lemmatize(text)
  return text

In [0]:
df1 = df[:50]

In [9]:
df1['fileprocessed'] = df1['file'].apply(toktoktok)
df1['messageprocessed'] = df1['message'].apply(toktoktok)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [10]:
df1.head()

file  ...                                   messageprocessed
0     allen-p/_sent_mail/1.  ...  message id                          javamail e...
1    allen-p/_sent_mail/10.  ...  message id                          javamail e...
2   allen-p/_sent_mail/100.  ...  message id                          javamail e...
3  allen-p/_sent_mail/1000.  ...  message id                          javamail e...
4  allen-p/_sent_mail/1001.  ...  message id                          javamail e...

[5 rows x 4 columns]

In [0]:
tf = TfidfVectorizer()

In [0]:
X = tf.fit_transform(df1['messageprocessed'])

In [0]:
X = pd.DataFrame(X.toarray(), columns = tf.get_feature_names())

In [14]:
X

ability      able     about  ...     zarin     zimam    zoning
0    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1    0.0000  0.000000  0.057154  ...  0.000000  0.000000  0.000000
2    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5    0.0000  0.000000  0.147521  ...  0.000000  0.000000  0.000000
6    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
7    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
8    0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
9    0.0000  0.000000  0.000000  ...  0.000000  0.099639  0.000000
10   0.0000  0.000000  0.000000  ...  0.138985  0.000000  0.000000
11   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
12   0.1509  0.000000  0.000000  ...  0.000000  0.000000  0.000000
13   0.1509  0.000000  0.000000  ...  0.000000  0.000000  0.000000
14   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
15   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
16   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
17   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
18   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
19   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
20   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
21   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
22   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
23   0.0000  0.035390  0.000000  ...  0.000000  0.000000  0.000000
24   0.0000  0.035264  0.000000  ...  0.000000  0.000000  0.000000
25   0.0000  0.034629  0.000000  ...  0.000000  0.000000  0.000000
26   0.0000  0.034635  0.000000  ...  0.000000  0.000000  0.000000
27   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
28   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
29   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
30   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
31   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
32   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
33   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
34   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
35   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
36   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
37   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
38   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
39   0.0000  0.000000  0.102485  ...  0.000000  0.000000  0.000000
40   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
41   0.0000  0.000000  0.018104  ...  0.000000  0.000000  0.026903
42   0.0000  0.000000  0.072047  ...  0.000000  0.000000  0.000000
43   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
44   0.0000  0.000000  0.104480  ...  0.000000  0.000000  0.000000
45   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
46   0.0000  0.000000  0.082205  ...  0.000000  0.000000  0.000000
47   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
48   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
49   0.0000  0.000000  0.000000  ...  0.000000  0.000000  0.000000

[50 rows x 1621 columns]

In [0]:
nmf = NMF(n_components = 4, init ='nndsvd', random_state = 42 )

In [16]:
w = nmf.fit_transform(X)
print(w)

[[2.72681103e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.13140679e-01 0.00000000e+00 2.66327757e-01 4.37334450e-03]
 [2.75415373e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.15029946e-01 0.00000000e+00 1.48542071e-01 2.80095635e-02]
 [3.49787129e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.25200877e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.91945615e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.78232848e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.25533370e-01 1.97197862e-02 8.46139141e-03 0.00000000e+00]
 [9.82594858e-02 3.15408441e-02 1.83401369e-01 0.00000000e+00]
 [2.16531327e-01 0.00000000e+00 4.93007067e-02 0.00000000e+00]
 [1.41420086e-01 6.16935813e-03 1.21746438e-01 1.67282181e-02]
 [0.00000000e+00 1.59757122e-01 4.88310444e-01 0.00000000e+00]
 [0.00000000e+00 1.59757122e-01 4.88310444e-01 0.00000000e+00]
 [2.66403974e-01 0.00000000e+00 7.91389737e-02 0.00000000e+00]
 [2.75607835e-01 0.00000000e+00 0.00000000e+00 0.000000

In [17]:
h = nmf.components_
print(h)

[[0.         0.         0.05197308 ... 0.0170212  0.00407854 0.        ]
 [0.01546507 0.         0.         ... 0.         0.00037471 0.        ]
 [0.05031714 0.02653783 0.0127137  ... 0.         0.00574732 0.00525316]
 [0.         0.         0.0381227  ... 0.         0.         0.        ]]


In [0]:
lda = LatentDirichletAllocation(n_components = 5, random_state = 42)

In [19]:
lda.fit(X)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=5, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [20]:
lda.components_

array([[0.20000938, 0.20001407, 0.20060437, ..., 0.20002444, 0.20001659,
        0.20001126],
       [0.20000953, 0.20001428, 0.20001377, ..., 0.2000248 , 0.20001684,
        0.20001143],
       [0.20000928, 0.20001391, 0.20074779, ..., 0.20002417, 0.2000164 ,
        0.20001112],
       [0.20000933, 0.20001301, 0.20001254, ..., 0.20002244, 0.20001536,
        0.20001046],
       [0.50176318, 0.33986267, 0.78261908, ..., 0.33888963, 0.29957387,
        0.22685823]])