<a href="https://colab.research.google.com/github/universeatmyfeet/NLP/blob/master/Classwork/NLP_Classwork6_J051.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import nltk
from nltk import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import LabelEncoder, LabelBinarizer
from sklearn.metrics import classification_report, roc_auc_score
import string
from string import digits
from nltk.corpus import stopwords
import lightgbm as lgb

In [0]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('words')

In [0]:
#loading data
tweet = pd.read_csv('https://raw.githubusercontent.com/zfz/twitter_corpus/master/full-corpus.csv', error_bad_lines=False)
amazon = pd.read_json("http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz", lines=True)

In [0]:
#Removing irrelevant sentiments in twitter data
twitter = tweet[tweet['Sentiment']!='irrelevant']


In [0]:
def toktoktok(text):
  text= text.lower()
  text = text.translate(text.maketrans('','',digits))#removing digits
  text = text.translate(text.maketrans('', '', '!"@#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~1234567890'))
  return text
 

In [0]:
twitter['TweetTokens']= twitter['TweetText'].apply(toktoktok)

In [7]:
twitter['TweetTokens']

0       now all apple has to do is get swype on the ip...
1       apple will be adding more carrier support to t...
2       hilarious youtube video  guy does a duet with ...
3       rim you made it too easy for me to switch to a...
4       i just realized that the reason i got into twi...
                              ...                        
4537    madtruckman modern day autograph i like the wa...
4538     ways to use twitter for business httptcojyxko...
4539    log off facebook on twitter  but i think im bo...
4540         twitters dumb i dont like it  hush up justin
4541    its almost  where is your bong is it packed le...
Name: TweetTokens, Length: 3424, dtype: object

**CountVectorizer**

In [0]:
vectorizer = CountVectorizer(lowercase=True, stop_words=set(stopwords.words('english')))
X = vectorizer.fit_transform(twitter['TweetTokens'])

In [9]:
vectorizer.get_feature_names()[:10]

['aaa',
 'aaargh',
 'aac',
 'aalkhubaizi',
 'aapl',
 'abandoned',
 'abbas',
 'abbreviations',
 'ability',
 'able']

In [10]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
features = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

In [12]:
features.head()

aaa  aaargh  aac  aalkhubaizi  aapl  ...  версию  новую  представит  你好  透過
0    0       0    0            0     0  ...       0      0           0   0   0
1    0       0    0            0     0  ...       0      0           0   0   0
2    0       0    0            0     0  ...       0      0           0   0   0
3    0       0    0            0     0  ...       0      0           0   0   0
4    0       0    0            0     0  ...       0      0           0   0   0

[5 rows x 8498 columns]

In [0]:
X_train,X_test,y_train,y_test = tts(X,twitter['Sentiment'],test_size=0.3, random_state=30)

In [0]:
lala = y_test

In [0]:
x_train = pd.DataFrame(X_train.toarray(),columns=vectorizer.get_feature_names())
x_test = pd.DataFrame(X_test.toarray(),columns=vectorizer.get_feature_names())

**Random Forest Classifier**

In [0]:
ran = RandomForestClassifier()

In [74]:
ran.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [75]:
y_pred = ran.predict(x_test)
print(classification_report(ran.predict(x_test),y_test))#default threshold(0.5)

              precision    recall  f1-score   support

    negative       0.39      0.66      0.49       104
     neutral       0.93      0.78      0.85       867
    positive       0.24      0.53      0.33        57

    accuracy                           0.75      1028
   macro avg       0.52      0.66      0.56      1028
weighted avg       0.84      0.75      0.78      1028



In [0]:
#roc auc score function
def multiclass_roc_auc_score(y_test, y_pred, average='macro'):
  lb = LabelBinarizer()
  lb.fit(y_test)
  Y_test = lb.transform(y_test)
  y_pred = lb.transform(y_pred)
  return roc_auc_score(Y_test, y_pred, average=average)

In [77]:
multiclass_roc_auc_score(y_test, y_pred)

0.6425430818291856

In [0]:
le = LabelEncoder()
Y_test = le.fit_transform(y_test)

In [79]:
pred_ran = ran.predict_proba(x_test)
pred_ran

array([[0.        , 1.        , 0.        ],
       [0.        , 0.3       , 0.7       ],
       [0.        , 0.7       , 0.3       ],
       ...,
       [0.        , 0.9875    , 0.0125    ],
       [0.2       , 0.8       , 0.        ],
       [0.        , 0.93007576, 0.06992424]])

**LightGBM**

In [0]:
params = {
    "objective" : "multiclass",
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'num_class':3,
    'learning_rate':0.01,
    'max_depth': 7,
    'num_leaves': 127,
    'feature_fraction': 0.4,
    'bagging_freq': 10,
    'num_iterations':1000 ,
    'max_bin' : 32}

In [0]:
le = LabelEncoder()  
d_train = lgb.Dataset(x_train,le.fit_transform(y_train))


In [0]:
clf = lgb.train( params,d_train, 100)

In [0]:
preds = clf.predict(x_test)
best_preds= [np.argmax(line) for line in preds]

In [69]:
np.bincount((le.fit_transform(y_train)))

array([ 397, 1605,  394])

In [80]:
print(classification_report(le.inverse_transform(best_preds),lala))

              precision    recall  f1-score   support

    negative       0.25      0.56      0.34        77
     neutral       0.94      0.75      0.83       922
    positive       0.09      0.38      0.14        29

    accuracy                           0.72      1028
   macro avg       0.43      0.56      0.44      1028
weighted avg       0.87      0.72      0.78      1028



In [81]:
np.bincount((best_preds))

array([ 77, 922,  29])

In [82]:
preds = clf.predict(x_train)
best_preds_train= [np.argmax(line) for line in preds]
print(classification_report(le.inverse_transform(best_preds_train),y_train))

              precision    recall  f1-score   support

    negative       0.32      0.73      0.44       172
     neutral       0.97      0.74      0.84      2101
    positive       0.25      0.80      0.38       123

    accuracy                           0.74      2396
   macro avg       0.51      0.76      0.55      2396
weighted avg       0.88      0.74      0.79      2396



**Threshold = 0.6**

In [86]:
###for lgbm

print("Default Threshold for lgbm : \n",classification_report(le.inverse_transform(best_preds_train),y_train))
def thresh_1(array):
  a = []
  for i in range(len(array)):
    if max(array[i])>0.6:
      a.append(np.argmax(array[i]))
    else:
      a.append(2)
  return a
print("\n 0.6 Threshold for lgbm : \n",classification_report(le.inverse_transform(thresh_1(preds)),y_train))
      
###For RandomForest
pred_rf = ran.predict_proba(x_test)
print("Default Threshold for rf : \n",(classification_report(ran.predict(x_test),lala)))
print("\n 0.6 threshold for rf : \n",classification_report(le.inverse_transform(thresh_1(pred_rf)),lala) )

Default Threshold for lgbm : 
               precision    recall  f1-score   support

    negative       0.32      0.73      0.44       172
     neutral       0.97      0.74      0.84      2101
    positive       0.25      0.80      0.38       123

    accuracy                           0.74      2396
   macro avg       0.51      0.76      0.55      2396
weighted avg       0.88      0.74      0.79      2396


 0.6 Threshold for lgbm : 
               precision    recall  f1-score   support

    negative       0.12      0.85      0.21        55
     neutral       0.84      0.82      0.83      1637
    positive       0.59      0.33      0.43       704

    accuracy                           0.68      2396
   macro avg       0.52      0.67      0.49      2396
weighted avg       0.75      0.68      0.70      2396

Default Threshold for rf : 
               precision    recall  f1-score   support

    negative       0.39      0.66      0.49       104
     neutral       0.93      0.78      0

**Threshold = 0.7**

In [89]:
print("Default Threshold for lgbm : \n",classification_report(le.inverse_transform(best_preds_train),y_train))
def thresh_2(array):
  a = []
  for i in range(len(array)):
    if max(array[i])>0.7:
      a.append(np.argmax(array[i]))
    else:
      a.append(2)
  return a
print("\n 0.7 Threshold for lgbm : \n",classification_report(le.inverse_transform(thresh_2(preds)),y_train))
      
###For RandomForest
pred_rf = ran.predict_proba(x_test)
print("Default Threshold for rf : \n",(classification_report(ran.predict(x_test),lala)))
print("\n 0.7 threshold for rf : \n",classification_report(le.inverse_transform(thresh_2(pred_rf)),lala) )

Default Threshold for lgbm : 
               precision    recall  f1-score   support

    negative       0.32      0.73      0.44       172
     neutral       0.97      0.74      0.84      2101
    positive       0.25      0.80      0.38       123

    accuracy                           0.74      2396
   macro avg       0.51      0.76      0.55      2396
weighted avg       0.88      0.74      0.79      2396


 0.7 Threshold for lgbm : 
               precision    recall  f1-score   support

    negative       0.07      0.90      0.12        29
     neutral       0.71      0.86      0.78      1327
    positive       0.75      0.28      0.41      1040

    accuracy                           0.61      2396
   macro avg       0.51      0.68      0.44      2396
weighted avg       0.72      0.61      0.61      2396

Default Threshold for rf : 
               precision    recall  f1-score   support

    negative       0.39      0.66      0.49       104
     neutral       0.93      0.78      0

**Threshold = 0.8**

In [91]:
print("Default Threshold for lgbm : \n",classification_report(le.inverse_transform(best_preds_train),y_train))
def thresh_3(array):
  a = []
  for i in range(len(array)):
    if max(array[i])>0.8:
      a.append(np.argmax(array[i]))
    else:
      a.append(2)
  return a
print("\n 0.8 Threshold for lgbm : \n",classification_report(le.inverse_transform(thresh_3(preds)),y_train))
      
###For RandomForest
pred_rf = ran.predict_proba(x_test)
print("Default Threshold for rf : \n",(classification_report(ran.predict(x_test),lala)))
print("\n 0.8 threshold for rf : \n",classification_report(le.inverse_transform(thresh_3(pred_rf)),lala) )

Default Threshold for lgbm : 
               precision    recall  f1-score   support

    negative       0.32      0.73      0.44       172
     neutral       0.97      0.74      0.84      2101
    positive       0.25      0.80      0.38       123

    accuracy                           0.74      2396
   macro avg       0.51      0.76      0.55      2396
weighted avg       0.88      0.74      0.79      2396


 0.8 Threshold for lgbm : 
               precision    recall  f1-score   support

    negative       0.03      0.85      0.05        13
     neutral       0.42      0.92      0.58       737
    positive       0.92      0.22      0.35      1646

    accuracy                           0.44      2396
   macro avg       0.46      0.66      0.33      2396
weighted avg       0.76      0.44      0.42      2396

Default Threshold for rf : 
               precision    recall  f1-score   support

    negative       0.39      0.66      0.49       104
     neutral       0.93      0.78      0